/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Settings;

import java.awt.Color;
import javax.swing.JFrame;
import User_Interfaces.Customer_Form;

/**
 *
 * @author patli
 */
public class Settings_Form extends javax.swing.JFrame{
    
    String username;
    String userType;
    String password;
    
    public void setUsername(String username){
        this.username = username;
    }
    
    public void getUserType(String userType){
        this.userType = userType;
    }
    
    public void getPassword(String password){
        this.password  = password;
    }
    
    /**
     * Creates new form Account_Interface
     */
    public Settings_Form() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton_Cuser = new javax.swing.JButton();
        jButton_Rpersonal = new javax.swing.JButton();
        jButton_Cpswd = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        jButton_security = new javax.swing.JButton();
        jButton_Daccount = new javax.swing.JButton();
        loginLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton_Cuser.setBackground(new java.awt.Color(0, 153, 153));
        jButton_Cuser.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_Cuser.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Cuser.setText("Change Username");
        jButton_Cuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_CuserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_CuserMouseExited(evt);
            }
        });
        jButton_Cuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CuserActionPerformed(evt);
            }
        });

        jButton_Rpersonal.setBackground(new java.awt.Color(0, 153, 153));
        jButton_Rpersonal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_Rpersonal.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Rpersonal.setText("Request for Personal Info");
        jButton_Rpersonal.setMaximumSize(new java.awt.Dimension(100, 28));
        jButton_Rpersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_RpersonalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_RpersonalMouseExited(evt);
            }
        });
        jButton_Rpersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RpersonalActionPerformed(evt);
            }
        });

        jButton_Cpswd.setBackground(new java.awt.Color(0, 153, 153));
        jButton_Cpswd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_Cpswd.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Cpswd.setText("Change Password");
        jButton_Cpswd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_CpswdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_CpswdMouseExited(evt);
            }
        });
        jButton_Cpswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CpswdActionPerformed(evt);
            }
        });

        jButton_Back.setBackground(new java.awt.Color(0, 153, 153));
        jButton_Back.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_Back.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Back.setText("Back");
        jButton_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_BackMouseExited(evt);
            }
        });
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });

        jButton_security.setBackground(new java.awt.Color(0, 153, 153));
        jButton_security.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_security.setForeground(new java.awt.Color(255, 255, 255));
        jButton_security.setText("Security Methods");
        jButton_security.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_securityMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_securityMouseExited(evt);
            }
        });
        jButton_security.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_securityActionPerformed(evt);
            }
        });

        jButton_Daccount.setBackground(new java.awt.Color(0, 153, 153));
        jButton_Daccount.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_Daccount.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Daccount.setText("Delete Account");
        jButton_Daccount.setMaximumSize(new java.awt.Dimension(100, 28));
        jButton_Daccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_DaccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_DaccountMouseExited(evt);
            }
        });
        jButton_Daccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DaccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Cuser, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton_Cpswd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_security, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Rpersonal, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                                .addComponent(jButton_Daccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton_Cuser, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Cpswd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Rpersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButton_Daccount, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton_security, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        loginLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setText("Account Settings");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(loginLabel)
                .addGap(177, 177, 177))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(loginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CpswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CpswdActionPerformed
       Change_Password newPassword = new Change_Password();
       newPassword.getPassword(this.password);
       newPassword.setVisible(true);
       newPassword.pack();
       newPassword.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton_CpswdActionPerformed

    private void jButton_CpswdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CpswdMouseExited
        // set jbutton background
        jButton_Cpswd.setBackground(new Color(0, 153, 153));
    }//GEN-LAST:event_jButton_CpswdMouseExited

    private void jButton_CpswdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CpswdMouseEntered
        // set jbutton background
        jButton_Cpswd.setBackground(new Color(0, 255, 255));
    }//GEN-LAST:event_jButton_CpswdMouseEntered

    private void jButton_RpersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RpersonalActionPerformed
       // set jbutton background
        jButton_Cuser.setBackground(new Color(0, 153, 153));
    }//GEN-LAST:event_jButton_RpersonalActionPerformed

    private void jButton_RpersonalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RpersonalMouseExited
        // set jbutton background
        jButton_Rpersonal.setBackground(new Color(0, 153, 153));
    }//GEN-LAST:event_jButton_RpersonalMouseExited

    private void jButton_RpersonalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RpersonalMouseEntered
        // set jbutton background
        jButton_Rpersonal.setBackground(new Color(0, 255, 255));
    }//GEN-LAST:event_jButton_RpersonalMouseEntered

    private void jButton_CuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CuserActionPerformed
       
    }//GEN-LAST:event_jButton_CuserActionPerformed

    private void jButton_CuserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CuserMouseExited
        // set jbutton background
        jButton_Cuser.setBackground(new Color(0, 153, 153));
    }//GEN-LAST:event_jButton_CuserMouseExited

    private void jButton_CuserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CuserMouseEntered
        // set jbutton background
        jButton_Cuser.setBackground(new Color(0, 255, 255));
    }//GEN-LAST:event_jButton_CuserMouseEntered

    private void jButton_BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_BackMouseEntered
        // set jbutton background
        jButton_Back.setBackground(new Color(0, 255, 255));
    }//GEN-LAST:event_jButton_BackMouseEntered

    private void jButton_BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_BackMouseExited
        // set jbutton background
        jButton_Back.setBackground(new Color(0, 153, 153));
    }//GEN-LAST:event_jButton_BackMouseExited

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        if(userType.equals("Customer")){
            Customer_Form user = new Customer_Form();
            user.setUserName(username);
            user.setVisible(true);
            user.pack();
            user.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jButton_securityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_securityMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_securityMouseEntered

    private void jButton_securityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_securityMouseExited
        // set jbutton background
        jButton_security.setBackground(new Color(0, 153, 153));
    }//GEN-LAST:event_jButton_securityMouseExited

    private void jButton_securityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_securityActionPerformed
         // set jbutton background
        jButton_security.setBackground(new Color(0, 255, 255));
    }//GEN-LAST:event_jButton_securityActionPerformed

    private void jButton_DaccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_DaccountMouseEntered
         // set jbutton background
        jButton_Daccount.setBackground(new Color(0, 255, 255));
    }//GEN-LAST:event_jButton_DaccountMouseEntered

    private void jButton_DaccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_DaccountMouseExited
       // set jbutton background
        jButton_Daccount.setBackground(new Color(0, 153, 153));
    }//GEN-LAST:event_jButton_DaccountMouseExited

    private void jButton_DaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DaccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_DaccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Cpswd;
    private javax.swing.JButton jButton_Cuser;
    private javax.swing.JButton jButton_Daccount;
    private javax.swing.JButton jButton_Rpersonal;
    private javax.swing.JButton jButton_security;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel loginLabel;
    // End of variables declaration//GEN-END:variables
}
