/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User_Interfaces;

import java.awt.Color;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patli
 */
public class ShoppingList_Form extends javax.swing.JFrame {

    String storesPath = "C:\\SmartShoppersSystem\\database\\stores.csv";
    File storesFile = new File(storesPath);
    
    String itemsPath = "C:\\SmartShoppersSystem\\database\\items.csv";
    File itemsFile = new File(itemsPath);
    
    String originalStoreID;
    String originalStoreName;
    
    public void getStoreID(String storeID){
        this.originalStoreID = storeID;
    }
    
    public void getStoreName(String storeName){
        this.originalStoreName = storeName;
        StoreNameLabel.setText("Store Name: " + this.originalStoreName);
    }
    
    /**
     * Creates new form ShoppingList_Form
     */
    public ShoppingList_Form() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Back1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_ShoppingListTable = new javax.swing.JTable();
        jButton_AddItem = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_ItemsTable = new javax.swing.JTable();
        customerLabel1 = new javax.swing.JLabel();
        customerLabel3 = new javax.swing.JLabel();
        jButton_RemoveItem = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        customerLabel4 = new javax.swing.JLabel();
        customerLabel5 = new javax.swing.JLabel();
        jButton_Back2 = new javax.swing.JButton();
        StoreNameLabel = new javax.swing.JLabel();

        jButton_Back1.setBackground(new java.awt.Color(0, 0, 204));
        jButton_Back1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_Back1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Back1.setText("Back");
        jButton_Back1.setMaximumSize(new java.awt.Dimension(100, 28));
        jButton_Back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_Back1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_Back1MouseExited(evt);
            }
        });
        jButton_Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Back1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 0, 204));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_ShoppingListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Store Name", "Address", "Opening", "Closing", "Item Availability"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_ShoppingListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ShoppingListTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_ShoppingListTable);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 480, 170));

        jButton_AddItem.setBackground(new java.awt.Color(204, 0, 204));
        jButton_AddItem.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_AddItem.setForeground(new java.awt.Color(255, 255, 255));
        jButton_AddItem.setText("Add Item to List");
        jButton_AddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_AddItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_AddItemMouseExited(evt);
            }
        });
        jButton_AddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddItemActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_AddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 170, 47));

        jTable_ItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Store Name", "Address", "Opening", "Closing", "Item Availability"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_ItemsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ItemsTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_ItemsTable);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 480, 170));

        customerLabel1.setBackground(new java.awt.Color(255, 255, 255));
        customerLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        customerLabel1.setText("Shopping List:");
        jPanel3.add(customerLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        customerLabel3.setBackground(new java.awt.Color(255, 255, 255));
        customerLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        customerLabel3.setText("Select Item from Shopping List:");
        jPanel3.add(customerLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 190, -1));

        jButton_RemoveItem.setBackground(new java.awt.Color(204, 0, 204));
        jButton_RemoveItem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton_RemoveItem.setForeground(new java.awt.Color(255, 255, 255));
        jButton_RemoveItem.setText("Remove Item from List");
        jButton_RemoveItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_RemoveItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_RemoveItemMouseExited(evt);
            }
        });
        jButton_RemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveItemActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_RemoveItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 47));

        jButton_Back.setBackground(new java.awt.Color(0, 0, 204));
        jButton_Back.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_Back.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Back.setText("Back");
        jButton_Back.setMaximumSize(new java.awt.Dimension(100, 28));
        jButton_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_BackMouseExited(evt);
            }
        });
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 90, 40));

        customerLabel4.setBackground(new java.awt.Color(255, 255, 255));
        customerLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        customerLabel4.setText("List of Items in Store:");
        jPanel3.add(customerLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        customerLabel5.setBackground(new java.awt.Color(255, 255, 255));
        customerLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        customerLabel5.setText("Select Item from Store Table:");
        jPanel3.add(customerLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jButton_Back2.setBackground(new java.awt.Color(0, 0, 204));
        jButton_Back2.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        jButton_Back2.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Back2.setText("Update Tables");
        jButton_Back2.setMaximumSize(new java.awt.Dimension(100, 28));
        jButton_Back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_Back2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_Back2MouseExited(evt);
            }
        });
        jButton_Back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Back2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_Back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 90, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 24, 700, 420));

        StoreNameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        StoreNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        StoreNameLabel.setText("Store Name:");
        jPanel2.add(StoreNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 340, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_BackMouseEntered
        // set jbutton background
        jButton_Back.setBackground(new Color(255, 102, 255));
    }//GEN-LAST:event_jButton_BackMouseEntered

    private void jButton_BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_BackMouseExited
        // set jbutton background
        jButton_Back.setBackground(new Color(0, 0, 204));
    }//GEN-LAST:event_jButton_BackMouseExited

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        Smart_Shoppers_System login = new Smart_Shoppers_System();
        login.setVisible(true);
        login.pack();
        login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jTable_ShoppingListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ShoppingListTableMouseClicked
        DefaultTableModel itemModel = (DefaultTableModel)jTable_ShoppingListTable.getModel();
    }//GEN-LAST:event_jTable_ShoppingListTableMouseClicked

    private void jButton_AddItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AddItemMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddItemMouseEntered

    private void jButton_AddItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AddItemMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AddItemMouseExited

    private void jButton_AddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddItemActionPerformed

    }//GEN-LAST:event_jButton_AddItemActionPerformed

    private void jTable_ItemsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ItemsTableMouseClicked
        DefaultTableModel itemModel = (DefaultTableModel)jTable_ShoppingListTable.getModel();
    }//GEN-LAST:event_jTable_ItemsTableMouseClicked

    private void jButton_RemoveItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RemoveItemMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_RemoveItemMouseEntered

    private void jButton_RemoveItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RemoveItemMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_RemoveItemMouseExited

    private void jButton_RemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_RemoveItemActionPerformed

    private void jButton_Back1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Back1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Back1MouseEntered

    private void jButton_Back1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Back1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Back1MouseExited

    private void jButton_Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Back1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Back1ActionPerformed

    private void jButton_Back2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Back2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Back2MouseEntered

    private void jButton_Back2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Back2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Back2MouseExited

    private void jButton_Back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Back2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Back2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShoppingList_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShoppingList_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShoppingList_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShoppingList_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShoppingList_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StoreNameLabel;
    private javax.swing.JLabel customerLabel1;
    private javax.swing.JLabel customerLabel3;
    private javax.swing.JLabel customerLabel4;
    private javax.swing.JLabel customerLabel5;
    private javax.swing.JButton jButton_AddItem;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Back1;
    private javax.swing.JButton jButton_Back2;
    private javax.swing.JButton jButton_RemoveItem;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_ItemsTable;
    private javax.swing.JTable jTable_ShoppingListTable;
    // End of variables declaration//GEN-END:variables
}
