/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import Models.User;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patli
 */
public class Customer_Form extends javax.swing.JFrame {
    
    String directoryPath = "C:\\SmartShoppersSystem\\database";
    File systemPath = new File(directoryPath);   //directory file path
    
    String loginPath = "C:\\SmartShoppersSystem\\database\\logins.csv";
    File loginFile = new File(loginPath);
    
    String storesPath = "C:\\SmartShoppersSystem\\database\\stores.csv";
    File storesFile = new File(storesPath);
    
    String itemsPath = "C:\\SmartShoppersSystem\\database\\items.csv";
    File itemsFile = new File(itemsPath);
    
    User currentUser;
    
    String userName;
    String password;
    String firstName;
    String lastName;
    String street;
    String Country;
    String city;
    String PostalCode;
    String userType = "Customer";
    String originalStoreName;
    String originalStoreID;
    
    public void getUser(User user){
        this.currentUser = user;
        this.userName = user.getUsername();
        customerLabel.setText("Customer: " + this.userName);
        this.password = user.getPassword();
        this.userType = user.getUserType();
        this.firstName = user.getFirstName();
        this.lastName = user.getLastName();
        this.street = user.getStreet();
        this.Country = user.getCountry();
        this.city = user.getCity();
        this.PostalCode = user.getPostalCode();
    }
    
    /**
     * Creates new form User_Interface
     */
    public Customer_Form() {
        initComponents();
        this.setLocationRelativeTo(null);
        updateStoreTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton_Logout = new javax.swing.JButton();
        jButton_AccountSettings = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_StoresTable = new javax.swing.JTable();
        jButton_Shop = new javax.swing.JButton();
        customerLabel = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 0, 204));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Logout.setBackground(new java.awt.Color(204, 0, 204));
        jButton_Logout.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_Logout.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Logout.setText("Logout");
        jButton_Logout.setMaximumSize(new java.awt.Dimension(100, 28));
        jButton_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_LogoutMouseExited(evt);
            }
        });
        jButton_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogoutActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 170, 47));

        jButton_AccountSettings.setBackground(new java.awt.Color(204, 0, 204));
        jButton_AccountSettings.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_AccountSettings.setForeground(new java.awt.Color(255, 255, 255));
        jButton_AccountSettings.setText("Account Settings");
        jButton_AccountSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_AccountSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_AccountSettingsMouseExited(evt);
            }
        });
        jButton_AccountSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AccountSettingsActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_AccountSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, 47));

        jTable_StoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Store Name", "StoreID", "Address", "Opening", "Closing", "Availability"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_StoresTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_StoresTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_StoresTable);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 500, 300));

        jButton_Shop.setBackground(new java.awt.Color(204, 0, 204));
        jButton_Shop.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_Shop.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Shop.setText("Shop");
        jButton_Shop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_ShopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_ShopMouseExited(evt);
            }
        });
        jButton_Shop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ShopActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_Shop, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 170, 47));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 44, 710, 350));

        customerLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        customerLabel.setForeground(new java.awt.Color(255, 255, 255));
        customerLabel.setText("Customer:");
        jPanel2.add(customerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AccountSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AccountSettingsActionPerformed
        Settings_Form accountSettings = new Settings_Form();
        accountSettings.getUser(currentUser);
        accountSettings.setVisible(true);
        accountSettings.pack();
        accountSettings.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_AccountSettingsActionPerformed

    private void jButton_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogoutActionPerformed
        Smart_Shoppers_System login = new Smart_Shoppers_System();
        login.setVisible(true);
        login.pack();
        login.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_LogoutActionPerformed

    private void jButton_LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LogoutMouseEntered
        // set jbutton background
        jButton_Logout.setBackground(new Color(255, 102, 255));
    }//GEN-LAST:event_jButton_LogoutMouseEntered

    private void jButton_LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LogoutMouseExited
        // set jbutton background
        jButton_Logout.setBackground(new Color(204, 0, 204));
    }//GEN-LAST:event_jButton_LogoutMouseExited

    private void jButton_AccountSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AccountSettingsMouseExited
        // set jbutton background
        jButton_AccountSettings.setBackground(new Color(204, 0, 204));
    }//GEN-LAST:event_jButton_AccountSettingsMouseExited

    private void jButton_AccountSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AccountSettingsMouseEntered
        // set jbutton background
        jButton_AccountSettings.setBackground(new Color(255, 102, 255));
    }//GEN-LAST:event_jButton_AccountSettingsMouseEntered

    private void updateStoreTable(){   
        try {
            DefaultTableModel csvData = new DefaultTableModel();

            if(csvData.getColumnCount() == 0 && storesFile.length() == 0){
                csvData.addColumn("Store Name");
                csvData.addColumn("Store Number");
                csvData.addColumn("Address");
                csvData.addColumn("Opening");
                csvData.addColumn("Closing");
                csvData.addColumn("Availability");
            }else{
                Scanner fileScan = new Scanner(storesFile);
            
                int start = 0;

                while (fileScan.hasNextLine()) {
                    String input = fileScan.nextLine();
                    String[] userValues = input.split(",");
                    
                    String storeName = userValues[0];
                    String storeNum = userValues[1];
                    String address = userValues[3];
                    String openingHours = userValues[4];
                    String closingHours = userValues[5];
                    String itemAvilability = userValues[6];

                    if(start == 0){
                        start = 1;
                        csvData.addColumn("Store Name");
                        csvData.addColumn("Store Number");
                        csvData.addColumn("Address");
                        csvData.addColumn("Opening");
                        csvData.addColumn("Closing");
                        csvData.addColumn("Availability");
                    }
                    else{
                        Vector row = new Vector();
                        row.add(storeName);
                        row.add(storeNum);
                        row.add(address);
                        row.add(openingHours);
                        row.add(closingHours);
                        row.add(itemAvilability);
                        csvData.addRow(row);
                    }
                }
            }
            jTable_StoresTable.setModel(csvData);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Admin_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jTable_StoresTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_StoresTableMouseClicked
        DefaultTableModel storeModel = (DefaultTableModel)jTable_StoresTable.getModel();
        this.originalStoreName = storeModel.getValueAt(jTable_StoresTable.getSelectedRow(), 0).toString();
        this.originalStoreID = storeModel.getValueAt(jTable_StoresTable.getSelectedRow(), 1).toString();
    }//GEN-LAST:event_jTable_StoresTableMouseClicked

    private void jButton_ShopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ShopMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ShopMouseEntered

    private void jButton_ShopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ShopMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ShopMouseExited

    private void jButton_ShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ShopActionPerformed
        if(jTable_StoresTable.getSelectedRowCount() == 1){
            ShoppingList_Form list = new ShoppingList_Form();
            list.getInfo(this.currentUser, this.originalStoreID, this.originalStoreName);
            list.setVisible(true);
            list.pack();
            list.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Select a Shop.", "Error Message", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton_ShopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Customer_Form().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerLabel;
    private javax.swing.JButton jButton_AccountSettings;
    private javax.swing.JButton jButton_Logout;
    private javax.swing.JButton jButton_Shop;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_StoresTable;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
